// In this file you can specify the trial data for your experiment


const trial_info = {
    key_press_m: [
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/1_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 1
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/1_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 2
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/1_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 3
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/1_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 4
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/2_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 5
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/2_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 6
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/2_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 7
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/2_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 8
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/3_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 9
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/3_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 10
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/3_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 11
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/3_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 12
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/4_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 13
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/4_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 14
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/4_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 15
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/4_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 16
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/5_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 17
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/5_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 18
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/5_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 19
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/5_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 20
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/6_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 21
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/6_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 22
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/6_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 23
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/6_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 24
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/7_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 25
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/7_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 26
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/7_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 27
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/7_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 28
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/8_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 29
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/8_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 30
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/8_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 31
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/8_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 32
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/9_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 33
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/9_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 34
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/9_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 35
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/9_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 36
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/10_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 37
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/10_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 38
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/10_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 39
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/10_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 40
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/11_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 41
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/11_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 42
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/11_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 43
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/11_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 44
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/12_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 45
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/12_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 46
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/12_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 47
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/12_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 48
        }
    ],
    key_press_p: [
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/13_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 49
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/13_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 50
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/13_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 51
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/13_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 52
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/14_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 53
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/14_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 54
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/14_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 55
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/14_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 56
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/15_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 50,
            pic_nr: 57
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/15_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 50,
            pic_nr: 58
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/15_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            rotation: 150,
            pic_nr: 59
        },
        {
            question: "Do these two objects have the same shape?",
            picture: "images/mental_rotation_images/15_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            rotation: 150,
            pic_nr: 60
        }
      ]
};
